# Generated by Django 3.0.5 on 2020-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('color', models.CharField(max_length=30, verbose_name='color')),
                ('description', models.TextField(verbose_name='description')),
                ('type', models.IntegerField(verbose_name='type')),
                ('points', models.IntegerField(verbose_name='points')),
                ('auction_title', models.TextField(verbose_name='auction_title')),
            ],
        ),
    ]
